  name: Install and configure NGINX
- hosts: webservers
  become: true
  vars:
    nginx_port: 80
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install nginx
      apt:
        name: nginx
        state: present
        notify:
        - Start NGINX

    - name: Configure nginx from template
      template:
        src: /path/nginx.conf.j2
        dest: /etc/nginx/nginx.conf

    - name: Copy a file from local to remote
      copy:
        src: /path/index.html
        dest: /index.html
        owner: www-data
        group: www-data
        mode: '0644'    

      handlers:
        - name: Start NGINX
        service:
          name: nginx
          state: started
          enabled: true
